### ISSUE TITLE
Only 1800 examples annotated

### ISSUE THREAD

**Issue by saketgupta1008** [pducanh/cornell_annotated_data#1]
Out of 11000 sentences, only 1800 are annotated.

**Comment by pducanh-bspoke** [comment]
You are right! The wrong file is uploaded. I will try to address this quickly

**Comment by pducanh** [comment]
You are right! It seems like the wrong file is uploaded. I will address the issue soon

**Comment by pducanh** [comment]
@saketgupta1008 I've uploaded the correct file. The previous file was suppose to be testing data only

**Comment by saketgupta1008** [comment]
Many thanks!
